require('dotenv').config();
const ADMIN_ID = parseInt(process.env.ADMIN_ID) || 8004114088;
const BOT_NAME = 'HelpDesk';
const BOT_USERNAME = 'HelpDesk_Bot';

const STATES = {
  IDLE: 'IDLE',
  SELECTING_CATEGORY: 'SELECTING_CATEGORY',
  WRITING_SUBJECT: 'WRITING_SUBJECT',
  WRITING_MESSAGE: 'WRITING_MESSAGE',
  IN_LIVE_CHAT: 'IN_LIVE_CHAT',
  RATING_TICKET: 'RATING_TICKET',
  ADMIN_REPLY_TICKET: 'ADMIN_REPLY_TICKET',
  ADMIN_BROADCAST_MSG: 'ADMIN_BROADCAST_MSG',
  ADMIN_BROADCAST_PHOTO: 'ADMIN_BROADCAST_PHOTO',
  ADMIN_MSG_USER_ID: 'ADMIN_MSG_USER_ID',
  ADMIN_MSG_USER_TEXT: 'ADMIN_MSG_USER_TEXT',
  ADMIN_ADD_CATEGORY: 'ADMIN_ADD_CATEGORY',
  ADMIN_ADD_FAQ_Q: 'ADMIN_ADD_FAQ_Q',
  ADMIN_ADD_FAQ_A: 'ADMIN_ADD_FAQ_A',
  ADMIN_ADD_QR_TITLE: 'ADMIN_ADD_QR_TITLE',
  ADMIN_ADD_QR_MSG: 'ADMIN_ADD_QR_MSG',
  ADMIN_BLOCK_REASON: 'ADMIN_BLOCK_REASON',
  ADMIN_TEMP_BLOCK_DUR: 'ADMIN_TEMP_BLOCK_DUR',
  ADMIN_SEARCH_USER: 'ADMIN_SEARCH_USER',
  ADMIN_ADD_NOTE: 'ADMIN_ADD_NOTE',
  ADMIN_IN_LIVE_CHAT: 'ADMIN_IN_LIVE_CHAT',
  ADMIN_SET_AUTO_REPLY: 'ADMIN_SET_AUTO_REPLY',
  ADMIN_RENAME_CATEGORY: 'ADMIN_RENAME_CATEGORY',
};

const STATUS_EMOJI = { OPEN: '🟢', IN_PROGRESS: '🔵', WAITING: '🟡', RESOLVED: '✅', CLOSED: '⛔' };
const PRIORITY_EMOJI = { LOW: '🔽', NORMAL: '➡️', HIGH: '🔼', URGENT: '🚨' };

module.exports = { ADMIN_ID, BOT_NAME, BOT_USERNAME, STATES, STATUS_EMOJI, PRIORITY_EMOJI };
